<a href="https://colab.research.google.com/github/Meexargha/AI-LAB-CODE-IIIT-G/blob/main/LAB6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Create a one-dimensional NumPy array containing the first 20 natural numbers. Compute its mean and standard deviation.
import numpy as np

a = np.arange(1, 21)

print("Array:", a)
print("Mean:", np.mean(a))
print("Standard Deviation:", np.std(a))

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Mean: 10.5
Standard Deviation: 5.766281297335398


In [2]:
#Create a 3 × 4 NumPy array using arange and reshape. Extract the second column using slicing.
import numpy as np

a = np.arange(12).reshape(3, 4)

print("Array:")
print(a)

print("Second column:")
print(a[:, 1])

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Second column:
[1 5 9]


In [3]:
#Given a 2 × 3 array, repeat each row twice and each column three times.
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

row_repeat = np.repeat(a, 2, axis=0)
col_repeat = np.repeat(a, 3, axis=1)

print("Rows repeated twice:")
print(row_repeat)

print("Columns repeated three times:")
print(col_repeat)

Rows repeated twice:
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]
Columns repeated three times:
[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


In [4]:
#Create two NumPy arrays of shapes (3,1) and (1,4). Add them using broadcasting and report the resulting shape.
import numpy as np

a = np.array([[1],
              [2],
              [3]])

b = np.array([[10, 20, 30, 40]])

c = a + b

print("Result:")
print(c)

print("Resulting shape:", c.shape)

Result:
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
Resulting shape: (3, 4)
